create extension if not exists pgcrypto;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    display_name text not null,
    password_hash text not null,
    created_at double precision not null default extract(epoch from now())
);

create table if not exists public.auth_tokens (
    token text primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    created_at double precision not null,
    expires_at double precision not null
);

create index if not exists auth_tokens_user_id_idx on public.auth_tokens(user_id);
create index if not exists auth_tokens_expires_at_idx on public.auth_tokens(expires_at);

create table if not exists public.interview_sessions (
    id uuid primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    mode text not null check (mode in ('mirror', 'interview', 'revision', 'streamer')),
    title text not null,
    status text not null check (status in ('active', 'completed')),
    started_at double precision not null,
    completed_at double precision,
    config_json jsonb,
    review_json jsonb
);

alter table public.interview_sessions add column if not exists config_json jsonb;
alter table public.interview_sessions drop constraint if exists interview_sessions_mode_check;
alter table public.interview_sessions
    add constraint interview_sessions_mode_check
    check (mode in ('mirror', 'interview', 'revision', 'streamer'));

create index if not exists interview_sessions_user_id_idx on public.interview_sessions(user_id);
create index if not exists interview_sessions_started_at_idx on public.interview_sessions(started_at desc);

create table if not exists public.session_samples (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.interview_sessions(id) on delete cascade,
    recorded_at double precision not null,
    emotion text not null,
    confidence double precision not null,
    metrics_json jsonb not null default '{}'::jsonb,
    scores_json jsonb not null default '{}'::jsonb
);

create index if not exists session_samples_session_id_idx on public.session_samples(session_id);
create index if not exists session_samples_recorded_at_idx on public.session_samples(recorded_at);

create table if not exists public.session_messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.interview_sessions(id) on delete cascade,
    role text not null check (role in ('system', 'assistant', 'user')),
    content text not null,
    created_at double precision not null
);

create table if not exists public.llm_usage_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    call_type text not null check (call_type in ('interview_start', 'transcription', 'interview_reply', 'interview_review')),
    created_at double precision not null
);

create index if not exists session_messages_session_id_idx on public.session_messages(session_id);
create index if not exists session_messages_created_at_idx on public.session_messages(created_at);
create index if not exists llm_usage_events_user_id_idx on public.llm_usage_events(user_id);
create index if not exists llm_usage_events_created_at_idx on public.llm_usage_events(created_at);

alter table public.users enable row level security;
alter table public.auth_tokens enable row level security;
alter table public.interview_sessions enable row level security;
alter table public.session_samples enable row level security;
alter table public.session_messages enable row level security;
alter table public.llm_usage_events enable row level security;

drop policy if exists service_role_full_access_users on public.users;
drop policy if exists service_role_full_access_auth_tokens on public.auth_tokens;
drop policy if exists service_role_full_access_interview_sessions on public.interview_sessions;
drop policy if exists service_role_full_access_session_samples on public.session_samples;
drop policy if exists service_role_full_access_session_messages on public.session_messages;
drop policy if exists service_role_full_access_llm_usage_events on public.llm_usage_events;

create policy service_role_full_access_users on public.users
for all to service_role
using (true)
with check (true);

create policy service_role_full_access_auth_tokens on public.auth_tokens
for all to service_role
using (true)
with check (true);

create policy service_role_full_access_interview_sessions on public.interview_sessions
for all to service_role
using (true)
with check (true);

create policy service_role_full_access_session_samples on public.session_samples
for all to service_role
using (true)
with check (true);

create policy service_role_full_access_session_messages on public.session_messages
for all to service_role
using (true)
with check (true);

create policy service_role_full_access_llm_usage_events on public.llm_usage_events
for all to service_role
using (true)
with check (true);